spring:
  application:
    name: product-service
  cloud:
    config:
      uri: http://localhost:8081
      username: root
      password: s3cr3t
  boot:
    admin:
      client:
        url: http://localhost:8086

server:
  port: 8091
  error:
    include-message: always
    include-binding-errors: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Deprecated config when we had application.yml
#spring:
#  h2:
#    console:
#      enabled: true
#
#  datasource:
#    url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate:
#        show_sql: true
#        use_sql_comments: false
#        format_sql: false
#
#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"